### ISSUE TITLE
Facebook use 

### ISSUE THREAD

**Issue by 3642066** [josex2r/github-project-card#3]
Would you teach me use this kind of json parsing so i can do the same with the Facebook Platform API ?
If you can, i will fork this now, and we will have a nice Facebook version of your card very fast .
Two versions, one for profiles and another one for pages ;)

**Comment by josex2r** [comment]
Not an issue.

Read the [Graph API](https://developers.facebook.com/docs/graph-api) and implement your own.

**Comment by 3642066** [comment]
I'm sorry, i dont use Github very well .
The Graph API i had already read .. but i also dont know how you parsed variables, i thought you could help me with that, but ok. Thank you .
